SAMPLE_RATE = 16000
CHANNELS = 1
CHUNK_SIZE = 1280

DURATION = 5

SILENCE_THRESHOLD = 500
SILENCE_THRESHOLD = 500

SILENCE_DURATION = 0.5
SILENCE_CHUNKS = int(
    SILENCE_DURATION * SAMPLE_RATE / CHUNK_SIZE
) + 1

SILENCE_CHUNKS = 13

SPEAKER_THRESHOLD = 0.6
WAKE_WORD_THRESHOLD = 0.5

DEVICE_NUMBER = 1